### ISSUE TITLE
source tarball for newer version

### ISSUE THREAD

**Issue by kbipinkumar** [dankelley/gri#19]
the Debian/ubuntu mirrors list the gri versions to be 2.12.27. however i can seem to finds source tarballs corresponding to the same. github lists latest release tag as [v2.12.23](https://github.com/dankelley/gri/releases/tag/v2.12.23). 

where can i find releases corresponding to the 2.12.27?

**Comment by dankelley** [comment]
Hello, and thanks for the query.

I am not good at making releases on github, because I work on the assumption that folks either want the very latest code (which is here, for general platforms) or they want the latest releases for various distributions (which will be provided by those distributions).

I see that the very latest commit to gri is by psg, who says it is a synch to 2.12.27-1, and so perhaps use that commit.  But, my guess is that if you are on debian/ubuntu then you likely want the source as supplied via that distribution mechanism.

I hope this is of some help to you.  Gri has been relatively unchanged for quite a few years, apart from adjustments that need to be made to the mechanisms that embed it in debian etc., to account for changes in the toolchain of that linux distribution.

**Comment by kbipinkumar** [comment]
i was trying to package gri for archlinux and was wondering about discrepancy between version in ubuntu repos and github release. that said i will attempt to build using the latest commit as suggested

**Comment by dankelley** [comment]
Good.  Closing issue now.
